### ISSUE TITLE
Impossible to hide axis label

### ISSUE THREAD

**Issue by SylvainBertrand** [GSI-CS-CO/chart-fx#115] opened 2020-03-04 05:03 UTC
This issue new with the version 11.1.2, wasn't there in 8.1.1.

The real issue is that there is no direct control over the visibility of the axis label.
From looking at the code, for instance `AbstractAxis.computePrefWidth(double)`, it seems that the intention is that if the text in `AbstractAxisParameter.axisLabel` is either null or empty, then the label would be hidden. However, after a call to `AbstractAxisParameter.updateAxisLabelAndUnit()`, the label can never be empty, thus can never be hidden as there no visible flag for it.

After running some debug, it seems that the only reason the issue didn't show up for me when using the version 8.1.1, is simply because `AbstractAxisParameter.updateAxisLabelAndUnit()` would never be called while when switching to 11.1.2, it appears to be called when initially rendering the chart.

The goal for me being to hide the axis labels, a workaround is to override the method `updateAxisLabelAndUnit()` and pretty much skip the update.

**Comment by RalphSteinhagen** [comment] 2020-03-04 07:46
Hi, 

this seems to be a duplicate of issue #105, is already fixed with commit #d4eaa6b and pushed to master.

The ticks and labels can be suppressed e.g. via:
`	DefaultNumericAxis yAxis = new DefaultNumericAxis();
    	yAxis.setTickLabelsVisible(false);
    	yAxis.setTickMarkVisible(false);
    	yAxis.setMinorTickVisible(false);
`
N.B. the grids are based on the computation of the major ticks, ie. suppressing the ticks also suppresses the corresponding grid lines.

We plan to do a release to Maven Central later this week. Meanwhile, you may give it a try using master and e.g. [SimpleChartSample.java](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-samples/src/main/java/de/gsi/chart/samples/SimpleChartSample.java) example (N.B. applied only for the y-axis):
![image](https://user-images.githubusercontent.com/46007894/75855982-b0086e00-5df3-11ea-9386-6e3c95b74cb8.png)

If you could give it a try.

**Comment by RalphSteinhagen** [comment] 2020-03-06 07:32
I close this issue since this seems to be fixed in master.

**Closed by RalphSteinhagen** 2020-03-06 07:32 UTC
Labels: invalid
