### ISSUE TITLE
The first and last bins of histograms are not drawn

### ISSUE THREAD

**Issue by karlduderstadt** [GSI-CS-CO/chart-fx#80] opened 2020-01-16 08:22 UTC
It seems that the first and last bins of histograms are not drawn. Is this the intended behavior of the render?

The following chart was generated with version 8.1.1 using the ErrorDataSetRenderer with two DefaultNumericAxis using PolyLineStyle LineStyle.HISTOGRAM and ErrorType ErrorStyle.NONE. The only dataset was a Histogram constructed using the double[] bins option to set the start and end position of all bins. It is just random sampling of a gaussian distribution.

<img width="726" alt="Screenshot 2020-01-16 at 09 06 15" src="https://user-images.githubusercontent.com/17951396/72505667-b68d5700-3840-11ea-90f5-bf26ae676d24.png">

**Comment by wirew0rm** [comment] 2020-01-16 13:17
I can reproduce. This seems to be 2 (or even 3) different problems. on the left, the bar appears when panning a little bit to the left, on the right it shows when point reduction is turned off (renderer.setPointReduction(false)) but the last line segment is missing.
![image](https://user-images.githubusercontent.com/1202371/72528234-dfc2dd00-386a-11ea-8923-631f2e2d3c27.png)

**Comment by wirew0rm** [comment] 2020-01-16 15:18
I got a partial fix, but there is a deeper problem with rendering histograms with non-equidistant bins. The dataset interface for Histograms returns the center and therefore the renderer cannot reproduce the actual binning. This will probably need some deeper api changes to get it right.

Your sample looks pretty equidistant, so if your usecase is equidistant use the min/max/nBins constructor which will give you an equidistant Histogram which internally works a little different.

**Comment by karlduderstadt** [comment] 2020-01-17 07:24
Thanks so much for your fast response and very helpful feedback! 

Yes, the bins are equidistant, so in principle the Histogram constructor that accepts min, max, and bin count would be ideal. Unfortunately, I ran into some trouble with that one which is why I switched to the constructor that just takes the list of bin boundaries.

When I plot the same data as I mentioned above with min = -2.0, max = 2.0, and bins = 10, I get the following histogram:
<img width="654" alt="Screenshot 2020-01-16 at 21 55 09" src="https://user-images.githubusercontent.com/17951396/72591833-7d68eb80-3901-11ea-8cd6-6fc919fed037.png">
As you can see all the bins are shifted toward the negative side by half a bin. I guess there is some shift introduced somewhere in the ErrorDataSetRenderer, unfortunately I haven't had time to look through and troubleshoot that code. I am sure you can more easily spot the issue and maybe fixing this would be a fast temporary solution.

Regarding the data reducer. For the current use case I turned it off and I don't think it is needed. I have noticed in general that if there are more than say 5-6 points in the dataset and second to last point is always skipped. Even with zooming way in etc. If you like I can make a separate issue about that. I just thought I would mention it since you might have to look into that based on your comments above.

**Comment by RalphSteinhagen** [comment] 2020-03-20 13:09
Hi @karlduderstadt, just as an update: 
the first/last bin not being drawn seems to be solved now by PR #132.

The issue of 'half-a-bin-shift' seems to occur only for the non-equidistant binning option which is a bit special. The latter does not (yet) provide the necessary API info of where to draw the specific edges and unfortunately, this cannot be automatically determined. This is different for the equidistant version where this is solved implicitly.

Hope this helps. The changes should be merged/published within the coming weeks.  Let us know if you have further questions or suggestions, otherwise, I'd like to close this issue.

**Comment by RalphSteinhagen** [comment] 2020-03-24 14:53
fixed by #132 and merged. closing issue

**Closed by RalphSteinhagen** 2020-03-24 14:53 UTC
Labels: bug:major

**Comment by karlduderstadt** [comment] 2020-03-29 12:52
Hi @RalphSteinhagen,

Thanks very much for fixing this issue. Once you make a new release, I will test the fix and report back. Unfortunately, I haven't been able to configure my environment properly to compile and test our the unreleased version.

**Comment by wirew0rm** [comment] 2020-03-30 08:46
You could also use the snapshot build, we have recently added some documentation for that to our README.md: https://github.com/GSI-CS-CO/chart-fx#using-the-snapshot-repository

But it also won't be that long before the next release, so you can definitely also wait for that.
Thanks for keeping in touch.

**Comment by karlduderstadt** [comment] 2020-05-09 08:06
So I finally had a chance to update to version 8.1.4 and test the histogram again. We use them everyday, but I just didn't have a chance to test to new version until now.

The first bin draws!! So that seems to be fixed. However, the last bin still don't draw for me. See image below:

![Screenshot 2020-05-09 at 10 02 47](https://user-images.githubusercontent.com/17951396/81467945-6ca7f280-91dc-11ea-9d05-c4fbc7dff8d3.png)

Am I missing something here. Is there some other way I should test this? Is there some way I can help. Perhaps if you point me to the relevant section of code, I can see if these is any solution I can implement on my side.

Again sorry I didn't test this earlier. Thanks very much for your efforts to fix this. You made such a wonderful charting library we rely completely on it a small library and gui we have written. Unfortunately, users have been complaining to me about the missing bins.

Thanks!!

**Comment by RalphSteinhagen** [comment] 2020-05-11 10:57
Hi @karlduderstadt 

I gave it a quick try and appears to work:
![image](https://user-images.githubusercontent.com/46007894/81553590-a9631d80-9385-11ea-873b-63b9c42e3f84.png)

Could you check this against the master and/or the JDK11 snapshot @wirew0rm mentioned above? Unfortunately, we haven't had the time to backport all recent changes to JDK8 yet but plan to do another x.1.5 release soonish. 

N.B. This will probably also the last x.1.y. release before we'll increase the minor number since we want to introduce some API changes w.r.t. handling of 3D datasets etc. If you have suggestions/feature requests... there is an open issue #44.
