### ISSUE TITLE
What is the professional way to invert xAxis values from max to min?

### ISSUE THREAD

**Issue by osaidmakhalfeh** [GSI-CS-CO/chart-fx#261] opened 2020-09-22 17:02 UTC
Hi Dears,
First of all I want to thank you again for this amazing work!

Here, I'm trying to draw the xAxis from the "Max" to the "Min" values.
I'm not sure, how can I do it easily? 

![inxax](https://user-images.githubusercontent.com/44381968/93913699-1ca27600-fd0e-11ea-9741-5c2946b7eb46.png)

Thanks a lot

**Comment by milo-gsi** [comment] 2020-09-22 17:41
Hi osaidmakhalfeh,

this a property of the axis.

See invertAxis(boolean)

**Comment by osaidmakhalfeh** [comment] 2020-09-22 18:40
> Hi osaidmakhalfeh,
> 
> this is a property of the axis.
> 
> See invertAxis(boolean)
Thanks a lot for your response.
I've done that before, but unfortunately, the numbers have disappeared from xAxis, here an eg.
![image](https://user-images.githubusercontent.com/44381968/93923360-f71c6900-fd1b-11ea-8fc8-477e51acd8cf.png)

**Comment by milo-gsi** [comment] 2020-09-22 18:43
Hi osaidmakhalfeh,

we just found that issue as I wanted to point you to one of the samples.
I'm sure it'll be fixed soon or @RalphSteinhagen / @wirew0rm will provide a workaround.

**Comment by RalphSteinhagen** [comment] 2020-09-22 18:58
@osaidmakhalfeh can you give it a try with the fixed version in the 'fix261' branch?

If you do not want to compile yourself, you can also use the snapshot repository as described [here](https://github.com/GSI-CS-CO/chart-fx#using-the-snapshot-repository). Just enable the snapshot repository and use `fix261-SNAPSHOT`for the version.

**Comment by RalphSteinhagen** [comment] 2020-09-22 19:12
... a fix a day keeps harm a way. 

@osaidmakhalfeh thanks for asking a question and triggering us to fix that issue. This must-have slipped in during one of the last commits and we did not catch this earlier.

Let us know if this fixes and helps with your particular application

**Comment by RalphSteinhagen** [comment] 2020-09-22 19:33
... now merged to master. Thanks to @milo-gsi for cross-checking.

**Comment by osaidmakhalfeh** [comment] 2020-09-23 11:27
A lot of thanks, Guys.
Now it works!

But there are a new icons that appeared after the fix.
![image](https://user-images.githubusercontent.com/44381968/94005786-75721d00-fda7-11ea-9396-fe1ec981801f.png)

 I'm not sure what is that, will try to solve it!
Thanks again.

**Comment by RalphSteinhagen** [comment] 2020-09-23 11:35
@osaidmakhalfeh this is unrelated and the normal expected behavior. The brackets '[]' contain the units ("" as a default in this case).

In case you want to suppress this, you may want to set `axis.setUnit(null);`.

**Comment by osaidmakhalfeh** [comment] 2020-09-23 12:31
> @osaidmakhalfeh this is unrelated and the normal expected behavior. The brackets '[]' contain the units ("" as a default in this case).
> 
> In case you want to suppress this, you may want to set `axis.setUnit(null);`.

That works! I mean it is related to the unit value on the axis.
Thanks again @RalphSteinhagen 

My last question to you -> I tried to draw a bar from that points on the charts, but here I'm facing a new problem:

![image](https://user-images.githubusercontent.com/44381968/94012495-917abc00-fdb1-11ea-946c-6d7865c6ce08.png)
 if you can see the dots on the top of the bar? any idea in how to remove it! or if you can reference me with a BarChart example.

Regards

**Comment by RalphSteinhagen** [comment] 2020-09-23 13:01
@osaidmakhalfeh these are the markers... can be controlled via `ErrorDataSetRenderer::setDrawMarker(boolean)` and other access methods (e.g. style, size, etc.)

**Comment by osaidmakhalfeh** [comment] 2020-09-23 13:13
> @osaidmakhalfeh these are the markers... can be controlled via `ErrorDataSetRenderer::setDrawMarker(boolean)` and other access methods (e.g. style, size, etc.)

I tried what you said. But unfortunately, I'm getting the same result! maybe it is something else? !
These are the steps I did:
![image](https://user-images.githubusercontent.com/44381968/94017072-a3f7f400-fdb7-11ea-810f-e6a5ac50ba7a.png)

**Comment by RalphSteinhagen** [comment] 2020-09-23 13:20
@osaidmakhalfeh is your project publically available or would you perhaps have an MVP sample?

**Comment by osaidmakhalfeh** [comment] 2020-09-23 14:10
> @osaidmakhalfeh is your project publically available or would you perhaps have an MVP sample?

To be honest with you, I'm on research about charts
Here I added my sample to a git repo that contains the barChart if you want to see it!

Thanks a lot @RalphSteinhagen 

https://github.com/osaidmakhalfeh/testChartsProject/tree/master/pcCharts/src/main/java

**Comment by RalphSteinhagen** [comment] 2020-09-23 17:05
@osaidmakhalfeh thanks for the link: :+1: 

You are using `DefaultErrorData`s and do not set the corresponding point errors (which default then to '0'). What you see are the squashed error bars (aka. as whiskers) around the point values and that are drawn by default by the `ErrorDataSetRenderer`. You can suppress these via:

```Java
errorRenderer2.setErrorType(ErrorStyle.NONE);
```

Also, you seem to use different DataSets to achieve different colours for a given range or particular values. This can be also achieved with one DataSet and the 'DataSet::addDataStyle(<index>,"fillColor=<...color...>");` option. Have a look at the samples for more options how you can modify the look-and-feel of the DataSets...

E.g. taken from your code-snippet:
```Java
    // [..]
    xAxes.invertAxis(true);
    final DoubleDataSet dataSet = new DoubleDataSet("dataSet");
    dataSet.setStyle("-fx-stroke: rgb(0, 0, 0)");

    for (int i = 0; i < 200; i++) {
      dataSet.add(i, i * 2);
      if (i < 10) {
        dataSet.addDataStyle(i, "fillColor=red; markerColor=red");
      } else if (i < 50) {
        dataSet.addDataStyle(i, "fillColor=blue; markerColor=blue");
      } else {
        dataSet.addDataStyle(i, "fillColor=green; markerColor=green");
      }
    }

    errorRenderer2.getDatasets().addAll(dataSet);
    errorRenderer2.setPolyLineStyle(LineStyle.NONE);
    errorRenderer2.setErrorType(ErrorStyle.NONE);

    errorRenderer2.setDrawMarker(false);
    errorRenderer2.setDrawBars(true);
    errorRenderer2.setDynamicBarWidth(false);
    errorRenderer2.setBarWidth(5);
    errorRenderer2.setShowInLegend(false);
    errorRenderer2.setPointReduction(false);
    // [..]
```
yields:
![image](https://user-images.githubusercontent.com/46007894/94044228-27244480-fdce-11ea-80df-ecfb0105a446.png)

In case you need three DataSets, then it might be better that each DataSet has a data point definition for each x-value (and the `y==Double.NaN` if not defined) or to attach each DataSet to a different ErrorDataSetRenderer. Otherwise, the relative bar-width calculation may get confused. You can set the bar width also to a fixed value as shown in the example snippet above (taken from your code).

Some random comments:
 * `StackPane` is not an ideal root container, since it doesn't manage (constrain) the size of its children. `Pane()`, `[H,V]Box` or similar seem to produce better results.
* DataSets should have either sorted data (before adding), or the ErrorDataSetRenderer be informed that the DataSets are not sorted (i.e. via 'ErrorDataSetRenderer::setAssumeSortedData(boolean)` ), or you can use one of the DataSets that sort the added data by default (e.g. [LimitedIndexedTreeDataSet](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-dataset/src/main/java/de/gsi/dataset/spi/LimitedIndexedTreeDataSet.java) or any other custom implementation).

Let us know if this helps your cause...

**Comment by osaidmakhalfeh** [comment] 2020-09-24 13:16
@RalphSteinhagen @milo-gsi 

Sure, it works.

I do not know what to say,
A lot of thanks to you guys wish you all the best forever.

**Comment by osaidmakhalfeh** [comment] 2020-09-24 13:16
@RalphSteinhagen @milo-gsi 

Sure, it works.

I do not know what to say,
A lot of thanks to you guys wish you all the best forever.

**Closed** 2020-09-24 13:16 UTC

**Comment by RalphSteinhagen** [comment] 2020-09-24 15:08
> A lot of thanks to you guys wish you all the best forever.

@osaidmakhalfeh hope this is not the last we are going to read from you. Hope the above has been useful and enjoyable!

Feel free to contact us if you have questions, bugs or just want to contribute to chart-fx (features, tutorials, examples, docs ...)

**Comment by osaidmakhalfeh** [comment] 2020-09-24 18:43
@RalphSteinhagen  sure, I think I can prepare now a good docs & tutorials for others, and I will send something to you very soon.
Thanks
