### ISSUE TITLE
Problem with the used version slf4j

### ISSUE THREAD

**Issue by tms-bonn** [GSI-CS-CO/chart-fx#498] opened 2022-03-16 10:55 UTC
**Describe the bug**
We use slf4j in last stable version 1.7.36.
In Chart-Fx they use slf4j 2.0.0-alpha. For what reason? This is explicitly marked as expiremental/unstable.
We cannot use unstable versions.
Is there any way to use chart-fx anyway?

**To Reproduce**
Use last stable version of slf4j (1.7.36) in your project.
 
``` java
Exception in thread "JavaFX Application Thread" java.lang.NoSuchMethodError: 'org.slf4j.spi.LoggingEventBuilder org.slf4j.Logger.atDebug()'
	at de.gsi.chart.axes.spi.DefaultNumericAxis.calculateMajorTickValues(DefaultNumericAxis.java:452)
	at de.gsi.chart.axes.spi.AbstractAxis.computeTickMarks(AbstractAxis.java:592)
	at de.gsi.chart.axes.spi.AbstractAxis.recomputeTickMarks(AbstractAxis.java:1278)
	at de.gsi.chart.axes.spi.AbstractAxis.recomputeTickMarks(AbstractAxis.java:392)

```

**Environment:**
 - OS: Oracle Linux 8
 - Java version: OpenJDK 17
 - JavaFx version: 17.0.2
 - ChartFx version: 11.2.6

**Comment by wirew0rm** [comment] 2022-03-16 12:13
slf4j 2 provides a very nice fluent logging API, which we really like and is in fact really stable compared to other dependencies. According to the documentation it should be backwards compatible (https://www.slf4j.org/manual.html#compatibility) but we also noticed that this is actually not valid for the 2.x versions. This was also reported upstream to slf4j: https://jira.qos.ch/browse/SLF4J-495.
There is not much we can do about this other than rewriting all of chart-fx's logging to use the non-fluent api or remove logging alltogether.

**Comment by tms-bonn** [comment] 2022-03-16 12:44
Ok,
dann ist es für uns leider keine Alternative.
Dann sind wir gezwungen jfreechart zu verwenden.
In meinen Augen sollte eine Bibliothek keine unstabile Abhängigkeiten verwenden.
In unserem Projekt haben wir vertraglich vereinbart nur stabile und LTS Versionen zu verwenden.

**Comment by RalphSteinhagen** [comment] 2022-03-16 18:26
@tms-bonn it's a pity that the slf4j logging wrapper in its newer 2.x version doesn't fit your use-case.

JFreeChart is also a very good and in the good company of many other mature charting libraries that we can recommend.

As mentioned, the SLF4J version we use has proven to be feature-rich and mature enough notably, since it's a logger wrapper, not a logging library itself, and thus not critical. Also, we did not start with an outdated dependency as we intend to develop, upgrade, and optimize a modern library that we want to use and continue to develop for at least the coming next 10 years. We trust in your understanding.

I will close this now, since this is not a bug. 

Feel free to share your use-case, application repo, or questions you may have in the [Discussions](https://github.com/GSI-CS-CO/chart-fx/discussions).

**Closed by RalphSteinhagen** 2022-03-16 18:26 UTC
