### ISSUE TITLE
Time axis does not handle negative values

### ISSUE THREAD

**Issue by ennerf** [GSI-CS-CO/chart-fx#37] opened 2019-09-18 11:14 UTC
The time axis (e.g. `xAxis.setTimeAxis(true)`) does not handle negative values. I've so far run into this in two cases:

* When a plot starts at time zero and a user tries to zoom out. That causes the bounds to go negative and throw an error.

```
Exception in thread "JavaFX Application Thread" java.time.DateTimeException: Invalid value for NanoOfSecond (valid values 0 - 999999999): -100000000
  at java.base/java.time.temporal.ValueRange.checkValidValue(Unknown Source)
  at java.base/java.time.temporal.ChronoField.checkValidValue(Unknown Source)
  at java.base/java.time.LocalDateTime.ofEpochSecond(Unknown Source)
  at de.gsi.chart.axes.spi.format.DefaultTimeFormatter.getTimeString(DefaultTimeFormatter.java:126)
  ...
```

* When showing a fixed window size where the time starts at zero, i.e., the left bound for a 10 second window would begin at -10 seconds.

**Comment by wirew0rm** [comment] 2019-09-18 12:55
As I suppose you are not showing dates from the 1970s you are experiencing this with an uninitialized chart? This is probably why this didn't show up earlier, but of course this should be handled gracefully without throwing error messages.

If your time is not unix epoch timestamps, setTimeAxis(true) should not be called. Maybe date/epoch/timestamp Axis would be less ambigious names for this functionality. And documentation should definitely be improved. (see also: #22)

@RalphSteinhagen when looking at this, I realized that the TimeAxisSample also has some problems (in master and dev). It becomes unresponsive when zooming with the scroll wheel and zoom actions generally do not work as intended.

**Comment by ennerf** [comment] 2019-09-18 13:20
I figured the time axis would be generally applicable to any time data. I'm often using relative time, e.g., time from whenever the first data point starts. 

![image](https://user-images.githubusercontent.com/5491587/65151835-2a505c00-da27-11e9-8f69-3bc579779a98.png)

Aside from the (easy-to-fix) negative number issue, starting at 0 seconds works just fine in the current implementation. Is there any reason why it needs to be limited to absolute timestamps?

**Comment by wirew0rm** [comment] 2019-09-18 13:49
I guess mostly because that was the assumption when the functionality was written, so you might run into cases that are wrong or at least not well tested.

One obvious (while maybe a bit constructed) example might be, that if you plot a data interval longer than the time from EPOCH to the first leap day afterwards, you will get wrong labels from this time on.
We try to make chart-fx output as independent of localization settings as possible, but there is a Timezone setting, which also could affect your output.
These are the potential problems i can think of on the spot.

Regarding your local fix, I see the problem that if you scroll out on a month timescale, you will get negative dates, which i now saw you probably also realized, returning an empty string is also what I would have proposed.
I will get some local feedback and get it merged if there are no objections.

**Closed** 2019-09-18 14:55 UTC
Labels: bug
