### ISSUE TITLE
Zoom starts on Y-Axis even if X-Axis only mode is applied

### ISSUE THREAD

**Issue by thhart** [GSI-CS-CO/chart-fx#358] opened 2021-02-12 10:19 UTC
Out of sudden the Y-Axis zooms as well. It looks like it is happening when data is refreshed (cleared from dataset and added again).

Version: 11.2.3

**Comment by thhart** [comment] 2021-02-12 10:56
Additional observation, clicking on the auto ranging button in the action bar does auto range the Y-Axis as well.

**Comment by wirew0rm** [comment] 2021-02-12 11:03
I could not reproduce this with our samples, so I can only make some wild guesses.

Do you lock your dataset while refreshing the data (`dataset.lock().writeLockGuard(() -> {...})`)? If not you could maybe confuse the Zoomer by modifying the data at a critical section.
Did you check the value of `zoomer.getAxisMode()` after you're seeing this wrong behaviour? Another one to check would be `zoomer.isAutoZoomEnabled()`, but it should default to false and I don't know why it should change without user interaction.

If this doesn't resolve the issue it would definitely help if you could provide a small, self contained sample or find a way to trigger this bug in one of our samples. I find comparing my code against the samples a good way to determine potential problems. Not that the samples are necessarily the best way to do things, but they kind of mark a beaten track as they are used in development and testing.

Your second observation is the intended behavior, i think. For interactive plots without any fixed axes, this is quite reasonable.
If you want to exclude an axis permanently from zooming you can use: `Zoomer.setOmitZoom(yAxis, true);` to exclude the Zoomer from ever modifying it.

**Comment by thhart** [comment] 2021-02-12 12:36
Will try to make a reproducible example and check the suggestion.

**Comment by wirew0rm** [comment] 2021-03-08 14:10
@thhart where you able to reproduce or resolve this issue?

**Comment by wirew0rm** [comment] 2021-06-25 11:35
Closing this as we cannot reproduce the issue without further information. Feel free to reopen with additional information.

**Closed by wirew0rm** 2021-06-25 11:35 UTC
