### ISSUE TITLE
chart-fx threads memory leak

### ISSUE THREAD

**Issue by AmjadMoqade98** [GSI-CS-CO/chart-fx#324] opened 2020-11-30 12:36 UTC
Hi everyone.
I have a memory problem with the charts. 
the chart-fx threads are not getting terminated when I close the charts view, thus the allocated stack memory by the threads is not getting released. 

this is a scenario of my case:
1 - I open a new Scene with two bar charts, two contour charts with no data on them.

charts:
![image](https://user-images.githubusercontent.com/48645435/100609065-10422700-3316-11eb-84b0-27e54fa91a09.png)

memory:
![image](https://user-images.githubusercontent.com/48645435/100609221-4e3f4b00-3316-11eb-8b0d-e461bc5aea3a.png)

2- add data to the charts.

charts:
![image](https://user-images.githubusercontent.com/48645435/100609277-68792900-3316-11eb-8f94-53ff78e624b8.png)

memory:
![image](https://user-images.githubusercontent.com/48645435/100609705-197fc380-3317-11eb-867d-6eb7283f4c2c.png)

3- move to other views by changing the parent of the current scene
memory:
![image](https://user-images.githubusercontent.com/48645435/100609705-197fc380-3317-11eb-867d-6eb7283f4c2c.png)

the chart-fx threads still occupy the memory.

4- open the charts view again with empty charts and  start reading  data ( the same data as the first time)
charts:
![image](https://user-images.githubusercontent.com/48645435/100609277-68792900-3316-11eb-8f94-53ff78e624b8.png)

memory:
![image](https://user-images.githubusercontent.com/48645435/100610113-c6f2d700-3317-11eb-8377-a92ede87edda.png)

I've tried some solutions but nothing worked for me.
I don't have a problem with heap memory.

**Comment by wirew0rm** [comment] 2020-11-30 14:58
I think you are misinterpreting the values in your screenshots.

This column does not show the stack space taken up by the threads (800 MB stack for the JavaFx Application Thread would be a lot, the jvm by default has 1MB of stack memory!). It shows the heap allocation per thread, but makes no statement about if this data was already garbage collected again. It might also now be used by a completely different thread.

So these values can only increase during the lifetime of the thread. ChartFx uses a thread pool (actually different thread pools for different parts of chartfx) so it does not have to recreate threads for every small computation task, which is why the threads are kept around.

But you are saying you have enough heap memory, so what is your actual memory problem? Do you get actual errors or where you just worried by the high numbers shown in your screenshots?

**Comment by AmjadMoqade98** [comment] 2020-12-02 09:47
thanks for your fast response!

sorry for the misunderstanding I thought it's not heap because when I enabled the heap logs the used memory there are not this big it's going from 20M to 1000M depending on the data size and it's getting collected well. 

the problem is when I monitor the app from the task manager in windows the used memory by the app is too high and it equals the sum of the used memory in the above screenshots. and after closing the scene that contains the charts the used memory will stay the same even if I cleared the data manually and set the charts reference to null and perform garbage collection manually.

**Comment by ennerf** [comment] 2020-12-02 10:08
The default GC likes to hold on to allocated memory and doesn't return it to the operating system. The newer [-XX:+UseZGC](https://wiki.openjdk.java.net/display/zgc/Main) collector returns memory pretty aggressively, so that may be worth trying out if you want to optimize for the task manager usage display.

**Comment by hhijawi** [comment] 2020-12-06 13:04
Hi Florian,
indeed using ZGC fixes the issue, I tried it and the memory is freed smoothly.
but unfortunately, we cannot use it as it is only supported in Windows 10.

is there another solution that can help?
cannot we destroy threads manually?

**Comment by ennerf** [comment] 2020-12-06 13:53
You can limit the maximum memory use with the `-Xmx` flag, e.g., `-Xmx512m`.

The only other way I'm aware of is to use native memory (e.g. direct buffers) that you can manually release via `sun.misc.Unsafe::invokeCleaner`. That won't help you with charts though, and you'd have to be careful to not cause any segfaults that would cause an application crash.

**Comment by pacher** [comment] 2020-12-06 15:45
@hhijawi It's the first time I hear that ZGC is only supported on Windows and could not find anything about that. Do you have a link around?
Anyway, there is also [Shenandoah](https://openjdk.java.net/projects/shenandoah/) from Red Hat.

**Comment by ennerf** [comment] 2020-12-06 15:58
I assumed @hhijawi  was referring to Windows 10 as in that it won't work on Windows 8.1. ZGC is definitely supported on Linux and macOS.

**Comment by hhijawi** [comment] 2020-12-06 18:01
https://openjdk.java.net/jeps/365

"Support for mapping paging-file backed memory into a reserved address space. The Windows memory management API is not as flexible as POSIX's mmap/munmap, especially when it comes to mapping file backed memory into a previously reserved address space region. To do this, ZGC will use the Windows concept of address space placeholders. The placeholder concept was introduced in version 1803 of Windows 10 and Windows Server. ZGC support for older versions of Windows will not be implemented."

**Comment by hhijawi** [comment] 2020-12-06 19:22
please note that I cannot also use Shenandoah, it is not supported in windows.

**Comment by ennerf** [comment] 2020-12-07 00:03
The issue you are seeing is caused by how legacy GCs allocate memory, and it is unrelated to this library. If you can't limit your max heap size (`-Xmx`), you can't use native memory, and you can't update to a modern GC, you are unfortunately out of luck.

I'd recommend watching one of Gil Tene's talks on garbage collection. The currently latest version seems to be [Really Understanding Garbage Collection](https://vimeo.com/374755640) from last year. The main takeaway for this issue would be at 52:00, i.e., "The secret to GC efficiency is empty memory".

It's also common practice to package different versions for each OS, e.g., Windows / macOS / Linux. You could enable ZGC by default, and have a fallback version for Windows 8 users that shows higher memory use.

**Comment by wirew0rm** [comment] 2020-12-18 09:32
Hey everyone, I will close this issue, as I think in the discussions it became clear, that this is more a question of how memory is handled in java and not a chart-fx specific problem.

Please feel free to reopen if you disagree or open a topic in our newly created [discussions forum](https://github.com/GSI-CS-CO/chart-fx/discussions) for more general discussions of the way chart-fx handles threads and memory.

Big thanks to Florian for chiming and for the talk recommendation :+1:

**Closed by wirew0rm** 2020-12-18 09:32 UTC
